[package]
name = "axo-sh"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.130"
dotenv = "0.15.0"
actix-web = "3.3.2"
diesel = { version = "1.4.8", features = ["r2d2", "mysql"] }
url = { version = "2.2.2", features = ["serde"] }
